### ISSUE TITLE
Don't mix camelCase and snake_case.

### ISSUE THREAD

**Issue by real2two** [fheahdythdr/modio.js#1]
The functions `email_request` and `email_exchange` are really out of place, because all of the other functions have variable names such as `setOAuthKey` and `getModDependencies`.

Renaming `email_request` and `email_exchange` to `emailRequest` and `emailExchange` would keep the library following a naming convention.

This looks like a pretty cool library though. Good luck on making this library. 👍

**Comment by fheahdythdr** [comment]
fixed, will keep that in mind for future functions
